### ISSUE TITLE
v1.0.0:SD_WU_6: tested on scidrive 2: get http status 500 error when copy and paste a file external link clicking extern al link icon to a new browser  

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#38]
I am not sure whether I do the right thing on not: here are the steps I have taken to produce this error:

1. select a file. 
2. click 'external link' icon.
3. copy the url and paste it on a new browser.
4. get HTTP status 500 error : javax.servlet.ServletException: java.lang.IllegalStateException: Target host must not be null, or set in parameters.
![er2](https://cloud.githubusercontent.com/assets/12955779/8735535/94a7c3b8-2bdf-11e5-835b-96442baca800.png)

**Comment by dmedv** [comment]
This is probably related to a known problem with the database. I know how to fix it, but I would prefer to create a separate database just for scidrive2, otherwise if I fix it in the current database, the old scidrive will definitely stop working, and other unknown and horrible things might happen...

**Comment by jkim485** [comment]
Tested and confirmed fix. Close issue.
